#
# docker-compose.ci.yml
#
# An override for using 'docker-compose.yml' in Cloud Build
#
# Intentions:
#   Allow the 'docker-compose.yml' file be used, from Cloud Build scripts,
#   so that the services are available to the following steps (using 'cloudbuild' network).
#
# References:
#   - Share Compose configurations between files and projects (Docker Compose docs)
#     -> https://docs.docker.com/compose/extends/
#
services:
  emul:
    # tbd. This is BROKEN at the moment. Want to use 'build' for the local development but 'image' for CI.
    #     Did not find a way to override 'build:' as if it wasn't provided. #later
    #image: ${CI_BUILDER_IMAGE:-firebase-ci-builder:11.0.1-node18-npm8}
    network_mode: cloudbuild
    container_name: emul

  warm-up:
    network_mode: cloudbuild
    container_name: warm-up
    environment:
      - WARM_UP_TIMEOUT=30000
      # seen durations of:
      #   17.341 s (fns:userInfo summary, CloudBuild)
      #   xxx ms (fns:greet, CloudBuild)

# warmed-up service not needed in CI
