#
# cloudbuild.yaml
#
# Intention:
#   Check that the project installs and runs the tests, using
#     - Node 16; npm 7
#
# Runtime environment:
#   - Current directory is '/workspace'
#   - env.variables (just some):
#     PWD=/workspace
#     HOME=/builder/home
#
# Triggers:
#   - functional changes to 'master' branch
#     - changes only affecting '.md' files are excluded
#

steps:
  # DEBUG
#- name: gcr.io/$PROJECT_ID/firebase-ci-builder:${_BUILDER_TAG}
#  entrypoint: bash
#  args: ['-c', 'env']

#--- Node 16 ---
#
- name: node:16-alpine
  entrypoint: npm
  args: ['install']

# Launch emul, keeps running in the background.
#
# Note: It's vital to wrap the command in Docker. This allows it to remain running for the rest of the steps.
#
- name: gcr.io/cloud-builders/docker
  args: [
    'run',
      '-d',
      '-p', '6767:6767', '-p', '5002:5002',
      '-v', '${_PWD}:/work', '-w', '/work',
      '--name', 'emul',
      '--network', 'cloudbuild',    # needed for showing the ports in the other steps
      'gcr.io/${PROJECT_ID}/firebase-ci-builder:${_BUILDER_TAG}',
    'npm', 'run', 'start'
  ]

- name: node:16-alpine
  entrypoint: npm
  args: ['run', 'ci:test']
  env:
    - EMUL_HOST=emul

# --- Timeout
#
# Cloud Build
#   (node 16):  1m53s, 1m58s (x2)
#
# Earlier versions
#   (node 16, DC):  2m7s, 2m9s
#   (node 14):  1m48s, 1m53s
#
timeout: 240s

substitutions:
  _BUILDER_TAG: 9.17.0-node16-npm7
  _PWD: /workspace
    # tbd. How to escape and use the 'PWD' env.var. in a command? #SO #help
